name: bench

on:
  push:
    - cabal.project
    - */benchmarks/**
    - */source/**
    - */*.cabal

jobs:
  benchmark:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install libsdl2-dev

    - uses: actions/checkout@v3

    - id: setup
      uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.2.4

    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cabal-store
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: |
        cabal update
        cabal build all --only-dependencies --enable-benchmarks

    - run: |
        cabal bench all --enable-tests --enable-benchmarks
        cat shaders/criterion.json \
          | jq '.[2][] | { name: .reportName, value: .reportAnalysis.anMean.estPoint }' \
          | jq -s . > benchmarks.json

    - uses: actions/cache@v1
      with:
        path: ./cache
        key: ${{ runner.os }}-benchmark

    - uses: benchmark-action/github-action-benchmark@v1
      with:
        tool: customSmallerIsBetter
        output-file-path: benchmarks.json
        external-data-json-path: ./cache/benchmark-data.json
        fail-on-alert: true
