name: build

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - run: sudo apt-get install libsdl2-dev

    - uses: actions/checkout@v3

    - id: setup
      uses: haskell/actions/setup@v2
      with:
        ghc-version: 9.2.4

    - uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cabal-store
        path: |
          ${{ steps.setup.outputs.cabal-store }}
          dist-newstyle
          ~/.ghcup

    - run: |
        cabal update
        cabal build all --only-dependencies

    - run: cabal build all
