name: lint

on:
  workflow_call:
    inputs:
      package:
        required: true
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        filters: |
          related:
          - '${{ inputs.package }}/**/*.hs'

    - if: steps.changes.outputs.related == 'true'
      uses: rwe/actions-hlint-setup@v1
      with:
        version: 3.5

    - if: steps.changes.outputs.related == 'true'
      uses: rwe/actions-hlint-run@v2
      with:
        path: shaders/
        fail-on: warning
